### ISSUE TITLE
RubyGems?

### ISSUE THREAD

**Issue by tubbo** [TheJumpCloud/jcapi-ruby#34]
Any reason why `jcapiv1` or `jcapiv2` isn't on RubyGems?

**Comment by kruggierojc** [comment]
Hi tubbo! My name is Kevin and I'm a Customer Success Engineer at JumpCloud. I don't see anything on our roadmap to create those gems but we would love to discuss this more with you! Could you please put this in an email and send it to us at support@jumpcloud.com or directly send our team a feature request? https://support.jumpcloud.com/support/s/article/to-submit-a-jumpcloud-feature-request2. Looking forward to hearing from you!
